# version: '3.8'
# services:
#   php:
#     image: php:8.1-fpm
#     volumes:
#       - ./:/var/www/html
#     networks:
#       - app-network

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./:/var/www/html/
#       - ./nginx:/etc/nginx/conf.d
#     depends_on:
#       - php
#     networks:
#       - app-network

#   mysql:
#     image: mysql:latest
#     environment:
#       MYSQL_ROOT_PASSWORD: hooyo123
#       MYSQL_DATABASE: database
#       MYSQL_USER: abdi
#       MYSQL_PASSWORD: hooyo123
#     ports:
#       - 4007:3306
#     networks:
#       - app-network

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     environment:
#       PMA_HOST: mysql
#       PMA_USER: root
#       PMA_PASSWORD: hooyo123
#     ports:
#       - "8080:80"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

version: '3.8'
services:
  php:
    image: php:8.1-fpm
    build:
      dockerfile: ./docker/php/dockerfile
      context: .
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: hooyo123
      MYSQL_DATABASE: cms
      MYSQL_USER: abdi
      MYSQL_PASSWORD: root
    ports:
      - 4007:3306
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: hooyo123
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    